// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jylovjshcdouxjdohehn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bG92anNoY2RvdXhqZG9oZWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjA0NTIsImV4cCI6MjA3MDEzNjQ1Mn0.yJBGnlTCPtO6z7jFPbGlRcIX397FoXBIBXyACvp5Cvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});